POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Patient was prescribed some nonsense.  It should work.",
  "date": "2020-04-07",
  "specialist": "Dr. Phil",
  "type": "Hospital",
  "discharge": {
    "date": "2020-04-21",
    "criteria": "Patient believes it is working."
  }
}