POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Patient is not yet showing symptoms of virus.",
  "date": "2018-07-12",
  "specialist": "Dr. Stoker",
  "type": "OccupationalHealthcare",
  "employerName": "Umbrella Corporation",
  "sickLeave": {
    "startDate": "2018-07-12",
    "endDate": "2018-07-15"
  }
}